import type { MetadataRoute } from "next";
import { ICON_SIZES, MASKABLE_SIZES, THEME_COLOR, iconPath, maskableIconPath } from "@/lib/pwa-assets";

// Web app manifest (PWA). Icons are generated by `pnpm icons`; sizes live in lib/pwa-assets.ts.
// Static per build, so name/description use the default locale (pt-BR).
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/generate",
    name: "Bigos Image",
    short_name: "Bigos",
    description: "Gere e edite imagens de um jeito simples.",
    lang: "pt-BR",
    start_url: "/generate",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    // Android builds its splash screen from this color and the icon.
    background_color: THEME_COLOR,
    theme_color: THEME_COLOR,
    icons: [
      ...ICON_SIZES.map((size) => ({
        src: iconPath(size),
        sizes: `${size}x${size}`,
        type: "image/png",
        purpose: "any" as const,
      })),
      ...MASKABLE_SIZES.map((size) => ({
        src: maskableIconPath(size),
        sizes: `${size}x${size}`,
        type: "image/png",
        purpose: "maskable" as const,
      })),
    ],
  };
}
