import type { MetadataRoute } from "next";

// Web app manifest (PWA). Icons are generated by `pnpm icons` from docs/icons/icon_warm.png.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Bigos Image",
    short_name: "Bigos",
    description: "Gere e edite imagens de um jeito simples.",
    lang: "pt-BR",
    start_url: "/gerar",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#ffffff",
    theme_color: "#ffc87c",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
